posts/urls.py
from django.urls import path, include

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='list'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('<int:userId>/', views.user_profile_view, name='profile'),
    path('<int:userId>/edit/', views.user_edit_view, name='edit'),
]

templates/components/messages.html
<div class="font-koho text-sm">
    {% for msg in messages %}
        {% if msg.tags == 'success' %}
            <div class="text-green-600">
                {{ msg }}
            </div>
        {% elif msg.tags == 'error' %}
            <div class="text-red-600">
                {{ msg }}
            </div>
        {% elif msg.tags == 'info' %}
            <div class="text-blue-600">
                {{ msg }}
            </div>
        {% elif msg.tags == 'warning' %}
            <div class="text-yellow-600">
                {{ msg }}
            </div>
        {% endif %}
    {% endfor %}
</div>

templates/components/navbar.html
<div class="bg-purple-600 text-white px-14 h-14 flex justify-between items-center shadow-lg font-noto">
    <div><h4 class="h6"><a href="{% url 'posts:list' %}">Social Club</a></h4></div>
    <div>
        {% if request.user.is_authenticated %}
            <a class="mr-5" href="{% url 'users:profile' userId=request.user.id %}">{{ request.user.username }}</a>
            <a class="" href="{% url 'users:logout' %}">Log Out</a>
        {% else %}
            <a class="mr-5" href="{% url 'users:login' %}">Log In</a>
            <a class="" href="{% url 'users:signup' %}">Sign Up</a>
        {% endif %}
    </div>
</div>